#ifndef GLOBALS_H
#define GLOBALS_H

#define debug true

// Speed of sound in m/s
// #define SOUND_SPEED 343     // Sound speed through air
#define SOUND_SPEED 1500    // Sound speed through water

// Acoustic Modem Serial Transmission Byte Lengths
#define STATUS_QUERY_PACKET_LENGTH 43
#define SET_ADDRESS_PACKET_LENGTH 5
#define PING_PACKET_LENGTH 11 // Verify this
#define BATTERY_VOLT_NOISE_MEAS_PACKET_LENGTH 0 // Test and update value

// Starts inclusive, ends exclusive

//Status Query
#define STATUS_QUERY_NODE_ADDR_START 2
#define STATUS_QUERY_NODE_ADDR_END 5
#define STATUS_QUERY_SUPPLY_VOLTAGE_START 5
#define STATUS_QUERY_SUPPLY_VOLTAGE_END 10
#define STATUS_QUERY_RELEASE_START 10
#define STATUS_QUERY_RELEASE_END 22
#define STATUS_QUERY_BUILD_DATE_START 22
#define STATUS_QUERY_BUILD_DATE_END 42

// Set Address
#define SET_ADDRESS_ADDR_START 2
#define SET_ADDRESS_ADDR_END 5

// Broadcast
#define BROADCAST_SRC_ADDR_START 2
#define BROADCAST_SRC_ADDR_END 5
#define BROADCAST_BYTE_LENGTH_START 5
#define BROADCAST_BYTE_LENGTH_END 7
#define BROADCAST_PACKET_DATA_START 7

#define BROADCAST_LOCAL_ECHO_LENGTH 4
#define BROADCAST_LOCAL_ECHO_BYTE_LENGTH_START 2
#define BROADCAST_LOCAL_ECHO_BYTE_LENGTH_END 4

// Unicast
#define UNICAST_BYTE_LENGTH_START 2
#define UNICAST_BYTE_LENGTH_END 4
#define UNICAST_PACKET_DATA_START 4

// Ping
#define PING_ADDR_START 2
#define PING_ADDR_END 5
#define PING_PROPOGATION_COUNTER_START 6
#define PING_PROPOGATION_COUNTER_END 11

#define PING_LOCAL_ECHO_LENGTH 5
#define PING_LOCAL_ECHO_DEST_ADDR_START 2
#define PING_LOCAL_ECHO_DEST_ADDR_END 5

#endif